# Generated by Django 4.0.4 on 2022-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_lead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(default='633214.jpg', upload_to=''),
        ),
    ]
